spring.application.name=student-library-management-system

server.port=7777

# 1. Database Connection String
spring.datasource.url=jdbc:mysql://localhost:3306/student_library_august2026

# 2. Database Credentials
spring.datasource.username=root
spring.datasource.password=root1234

# 3. Driver Class Name (Optional for newer Spring Boot versions)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Hibernate DDL Auto Strategy (none, update, create, create-drop, validate)
spring.jpa.hibernate.ddl-auto=update

# 5. Format and Show Executed SQL in the Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 6. Database Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect